using System;
using Microsoft.EntityFrameworkCore.Migrations;

namespace GoodBuyAPI.Migrations
{
    public partial class InitialCreate : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "EntriesList",
                columns: table => new
                {
                    ID = table.Column<decimal>(nullable: false),
                    Name = table.Column<string>(nullable: true),
                    Link = table.Column<string>(nullable: true),
                    CreatedDate = table.Column<DateTime>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_EntriesList", x => x.ID);
                });

            migrationBuilder.InsertData(
                table: "EntriesList",
                columns: new[] { "ID", "CreatedDate", "Link", "Name" },
                values: new object[,]
                {
                    { 8600742014093m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/brinza_serbskaya_serbskiy_dom/", "Брынза сербская \\\"Сербский дом\\\"" },
                    { 8004603100381m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_antichi_maestri_grana_padano/", "Сыр Antichi Maestri \\\"Grana Padano\\\"" },
                    { 4607074392442m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_zorka_adigeyskiy_delikatesniy/", "Сыр Zorka \\\"Адыгейский деликатесный\\\"" },
                    { 4607946840439m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_zdorove_iz_predgorya_fermerskiy/", "Сыр Здоровье из Предгорья \\\"Фермерский\\\"" },
                    { 3523230028431m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_koziy_soignon/", "Сыр козий Soignon" },
                    { 4820111642359m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_dobryana_zolotistiy/", "Сыр Добряна \\\"Золотистый\\\"" },
                    { 20933883m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_milbona_maasdam_finskiy/", "Сыр Milbona Маасдам финский" },
                    { 20014254m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_milbona/", "Сыр Milbona" },
                    { 2310369000930m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_novogrudskie_dari_pesto/", "Сыр Новогрудские Дары \\\"Песто\\\"" },
                    { 8692971434919m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_tureckiy_halk_taze_kasar_peyniri/", "Сыр турецкий Halk Taze Kasar Peyniri" },
                    { 4607127280054m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_myagkiy_rovenki_adigeyskiy_45/", "Сыр мягкий Ровеньки \\\"Адыгейский\\\" 45%" },
                    { 5760466827225m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_s_goluboy_plesenyu_castello_danish_blue_slivochniy/", "Сыр с голубой плесенью Castello Danish Blue \\\"Сливочный\\\"" },
                    { 3073781053821m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_leerdammer_llightlife_17/", "Сыр Leerdammer Llightlife 17%" },
                    { 6408432052705m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/kopcheniy_sir_viola_s_salyami/", "Копченый сыр Viola с салями" },
                    { 3272770003148m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/svezhiy_sir_iz_kozego_moloka_bongrain_chavroux/", "Свежий сыр из козьего молока Bongrain \\\"Chavroux\\\"" },
                    { 4606068378707m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_lenta_fermerskiy/", "Сыр Лента \\\"Фермерский\\\"" },
                    { 2393876003304m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_liebendorf_maasdam/?&capt4a=2", "Сыр LiebenDorf Маасдам" },
                    { 4650100420497m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_s_beloy_plesenyu_zhukovskoe_moloko_camambert_from_zhukovka/", "Сыр с белой плесенью Жуковское молоко Camambert from Zhukovka" },
                    { 2201956900545m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_cheese_life_mozzarella_pizza/", "Сыр Cheese Life \\\"Mozzarella Pizza\\\"" },
                    { 4607052402378m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/myagkiy_sir_pretto_maskarpone/", "Мягкий сыр Pretto \\\"Маскарпоне\\\"" },
                    { 2000000000626m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_podvore_mocarella/", "Сыр Подворье \\\"Моцарелла\\\"" },
                    { 4740142003786m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_epiim_edamjuusto/", "Сыр Epiim Edamjuusto" },
                    { 2104779003403m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_holod_adigeyskiy/", "Сыр Холод \\\"Адыгейский\\\"" },
                    { 4607044667426m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_suhoy_kopcheniy_foma_lukich_bochonok/", "Сыр сухой копченый Фома Лукич \\\"Бочонок\\\"" },
                    { 5900120061729m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_swiatowid_salami/", "Сыр Swiatowid Salami" },
                    { 4700000140053m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/kolbasniy_sir_belovodskiy_maslosirzavod/", "Колбасный сыр \\\"Беловодский маслосырзавод\\\"" },
                    { 2000063640012m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_dlya_zharki_myasnov_sernurskiy_halumis/", "Сыр для жарки МясновЪ \\\"Сернурский Халумис\\\"" },
                    { 4810904000480m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_kuvshinka_suluguni/", "Сыр Кувшинка \\\"Сулугуни\\\"" },
                    { 4810012003106m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_novogrudskie_dari_adigeyskiy_klassicheskiy/", "Сыр Новогрудские дары \\\"Адыгейский классический\\\"" },
                    { 4627128150040m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/soeviy_sir_edemskiy_sad_tofu/", "Соевый сыр Едемский сад \\\"Тофу\\\"" },
                    { 4740553698113m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_parmezan_valio_forte/", "Сыр пармезан Valio Forte" },
                    { 7640106051211m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_myagkiy_moser_schweizer_huus_chasli_huus_chasli_s_beloy_plesenyu/", "Сыр мягкий Moser Schweizer Huus Chasli Хуус Часли с белой плесенью" },
                    { 8021398443905m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_igor_gorgonzola_piccante/", "Сыр Igor Gorgonzola Piccante" },
                    { 4607141170720m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_s_pazhitnikom_produkti_iz_yaroslavki_mologa/", "Сыр с пажитником Продукты из Ярославки \\\"Молога\\\"" },
                    { 4607022663242m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_president_la_brique/", "Сыр President La Brique" },
                    { 7617067036328m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_haidi_swiss_ceddar/", "Сыр Haidi Swiss Ceddar" },
                    { 4607025501992m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_myagkiy_sheksninskiy_maslozavod_adigeyskiy/", "Сыр мягкий Шекснинский маслозавод \\\"Адыгейский\\\"" },
                    { 4820009352636m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_tverdiy_zveni_gora_figura/", "Сыр твердый Звени Гора Фигура" },
                    { 40409801m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_s_goluboy_plesenyu_paladin_fromage_bleu/", "Сыр с голубой плесенью Paladin \\\"Fromage bleu\\\"" },
                    { 5900512130408m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/tverdiy_sir_biedronka_serovit_gouda/", "Твердый сыр Biedronka Serovit Gouda" },
                    { 7610563606392m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_le_superbe_services_ag_lustenberger_1862_fruity_tangy/", "Сыр Le Superbe Services AG \\\"Lustenberger 1862 fruity tangy\\\"" },
                    { 2844830000629m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_mifroma_sa_tet_de_muan/", "Сыр Mifroma Sa \\\"Тет де Муан\\\"" },
                    { 4680038890376m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_myagkiy_slivkin_dom_rikotta/", "Сыр мягкий Сливкин дом \\\"Рикотта\\\"" },
                    { 2100100147600m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_s_goluboy_plesenyu_izbenka_dzhersi_blyu/", "Сыр с голубой плесенью Избенка \\\"Джерси Блю\\\"" },
                    { 4603209002477m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_ruzskoe_moloko_ruzskiy_pryaniy/", "Сыр Рузское молоко \\\"Рузский\\\" Пряный" },
                    { 6402410119556m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_valio_oltermanni_29/", "Сыр Valio Oltermanni" },
                    { 2100100093068m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_myagkiy_rassolniy_izbenka_sirtos/", "Сыр мягкий рассольный Избенка Сиртос" },
                    { 4620016650448m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_market_perekrestok_mocarella/", "Сыр Маркет Перекресток \\\"Моцарелла\\\"" },
                    { 6260161533630m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/slivochniy_sir_kalleh/", "Сливочный сыр Kalleh" },
                    { 4000504149423m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_myagkiy_kaserei_champignon_cambozola_s_goluboy_plesenyu/", "Сыр мягкий Kaserei Champignon Cambozola с голубой плесенью" },
                    { 2100100073022m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_myagkiy_vkusvill_bri/", "Сыр мягкий ВкусВилл \\\"Бри\\\"" },
                    { 4520019492598m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/kislomolochniy_sir_belocerkovskiy_molokozavod_domashniy_5/", "Кисломолочный сыр Белоцерковский молокозавод \\\"Домашний\\\"" },
                    { 4607048552919m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_milkom_tilziter/", "Сыр Милком \\\"Тильзитэр\\\"" },
                    { 4740553691152m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_bezlaktozniy_valio_atleet/", "Сыр безлактозный Valio \\\"Atleet\\\"" },
                    { 4627075491061m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/bobrovskiy_sir_polutverdiy_slivochniy/", "Сыр полутвердый Бобровский \\\"Сливочный\\\"" },
                    { 5711953033926m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_arla_loputon_kermajuusto_17/", "Сыр Arla Loputon Kermajuusto" },
                    { 4811233001964m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_myagkiy_rassolniy_molodeya_mocarella/", "Сыр мягкий рассольный Молодея \\\"Моцарелла\\\"" },
                    { 4607050960818m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_kopcheniy_kosichka_ellazan/", "Сыр копченый косичка Эллазан" },
                    { 2370150010241m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_osobiy_sarmich_russkiy_sir_fasovanniy/", "Сыр особый Сармич \\\"Гурман\\\" фасованный" },
                    { 4820040746616m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_kislomolochniy_dobrinya_9/", "Сыр кисломолочный Добрыня" },
                    { 5902241216798m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_makro_chef_ser_camembert/", "Сыр Makro Chef Ser Camembert" },
                    { 4607052401302m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_unagrande_mocarella_chiledzhina/gallery/", "Сыр Unagrande \\\"Моцарелла Чильеджина\\\"" },
                    { 8023951002550m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_ghidetti_maskarpone/", "Сыр Ghidetti \\\"Маскарпоне\\\"" },
                    { 4620016651032m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_market_perekrestok_kamamber/", "Сыр Маркет Перекресток \\\"Камамбер\\\"" },
                    { 4650167850336m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_beloe_zoloto_adigeyskiy_iz_kozego_moloka/", "Сыр Белое Золото Адыгейский из Козьего молока" },
                    { 4607002022618m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_violife_legkiy/", "Сыр Violife \\\"Легкий\\\"" },
                    { 4660059528045m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_fermerskaya_kollekciya_rikotta_45/", "Сыр Фермерская коллекция \\\"Рикотта\\\" 45%" },
                    { 2999200013669m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_de_luxe_maasdam/", "Сыр De Luxe Maasdam" },
                    { 4607128362391m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_o_key_domashniy_po-kavkazski/", "Сыр ОКей Домашний по-кавказски" },
                    { 4610032582106m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_nikolaevskie_sirovarni_myagkiy_fermerskiy/", "Сыр Николаевские сыроварни \\\"Мягкий\\\" фермерский" },
                    { 2787241003424m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_piryatin_mramorniy/", "Сыр Пирятин \\\"Мраморный\\\"" },
                    { 5900512990224m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_mlekovita_salami/", "Сыр Mlekovita Salami" },
                    { 2100100030582m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/tofu_vkusvill_s_ukropom_i_chesnokom/", "Тофу ВкусВилл \\\"С укропом и чесноком\\\"" },
                    { 4606038038891m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_myagkiy_zelenaya_liniya_s_tomatom_i_bazilikom/", "Сыр мягкий Зеленая Линия с томатом и базиликом" },
                    { 4630061740896m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_dzhankoyskiy_sir_mocarella/", "Сыр Джанкойский сыр \\\"Моцарелла\\\"" },
                    { 4607052402392m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_myagkiy_unagrande_cacioricotta/", "Сыр мягкий Unagrande Cacioricotta" },
                    { 2100100102951m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_vkusvill_sbrinc/", "Сыр ВкусВилл \\\"Сбринц\\\"" },
                    { 2000243003101m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_radost_vkusa_rizhiy_chedder/", "Сыр Радость вкуса \\\"Рыжий Чеддер\\\"" },
                    { 4810904001418m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_landers_suluguni/", "Сыр Landers \\\"Сулугуни\\\"" },
                    { 4665296191991m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_s_beloy_plesenyu_fratelli_spirini_monblan/", "Сыр с белой плесенью Fratelli Spirini Монблан" },
                    { 4620016651018m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_perekrestok_mocarella_dlya_picci/", "Сыр Перекресток Моцарелла для пиццы" },
                    { 2100100005481m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_izbenka_gollandskiy/", "Сыр Избенка \\\"Голландский\\\"" },
                    { 4811832000795m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_kopcheniy_glubokskaya_pticefabrika_dzhil/", "Сыр копченый Глубокская птицефабрика \\\"Джил\\\"" },
                    { 3161712996146m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_ile_de_franse_petit_brie/", "Сыр ILE de Franse Petit Brie" },
                    { 4002174205379m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/shveycarskiy_sir_margot_fromages_sa_tete_de_moine/", "Швейцарский сыр Margot Fromages Sa Tete de Moine" },
                    { 4606068330194m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_lenta_adigeyskiy_kopcheniy/", "Сыр Лента Адыгейский копченый" },
                    { 2341573002267m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_archa_gauda/", "Сыр Арча \\\"Гауда\\\"" },
                    { 4607028304712m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_rovenki-maslosirzavod_fresh/", "Сыр Ровеньки-маслосырзавод Fresh" },
                    { 2100100159139m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_myagkiy_vkusvill_rikotta_s_shokoladom/", "Сыр мягкий ВкусВилл \\\"Рикотта с шоколадом\\\"" },
                    { 4680320008205m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_fasovanniy_tertiy_milken_mite_dlya_picci/", "Сыр фасованный тертый Milken Mite для пиццы" },
                    { 5703985070383m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_s_goluboy_plesenyu_danablu_mammen_ost/", "Сыр с голубой плесенью Danablu Mammen OST" },
                    { 465011743020m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_altayskie_sirovari_gollandskiy/", "Сыр Алтайские сыровары \\\"Голландский\\\"" },
                    { 4610032580072m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_nikolaevskie_sirovarni_kostromskoy/", "Сыр Николаевские сыроварни \\\"Костромской\\\"" },
                    { 4607052402880m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_market_perekrestok_suluguni/", "Сыр Маркет Перекресток \\\"Сулугуни\\\"" },
                    { 4601363002241m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_skit_skarmoca_cheldzhine_kopcheniy/", "Сыр Скит \\\"Скармоца Чьельджине\\\" копченый" },
                    { 4779024794696m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/produkt_veganskiy_regalio_s_zelenyu/", "Продукт веганский Regalio с зеленью" },
                    { 20532031m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_antichi_maestri_parmigiano_reggiano_dop/gallery/", "Сыр Antichi Maestri Parmigiano Reggiano DOP" },
                    { 4610004671449m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_sarmich_chedder/", "Сыр Сармич \\\"Чеддер\\\"" },
                    { 20536718m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_pilos_camembert_naturalniy/", "Сыр Pilos Camembert натуральный" },
                    { 2546953003487m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_beloslava_sirniy_aristokrat_50_vesovoy/gallery/", "Сыр Белослава \\\"Сырный аристократ\\\" 50%" },
                    { 2100100004163m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_izbenka_gran-pri/", "Сыр Избенка \\\"Гран-При\\\"" },
                    { 4607195114022m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_chaban_suluguni/", "Сыр Чабан \\\"Сулугуни\\\"" },
                    { 2100100162924m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_vkusvill_mocarella_perlini/", "Сыр ВкусВилл \\\"Моцарелла перлини\\\"" },
                    { 2510348003581m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_myagkiy_slivochniy_holifud_chezariya/", "Сыр мягкий сливочный ХолиФуд \\\"Чезария\\\"" },
                    { 8002004437259m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_biraghi_parmezan_biraghini_snack/", "Сыр Biraghi Пармезан Biraghini Snack" },
                    { 4630073930025m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_laime_switzerland_swiss_cheese/", "Сыр Laime Switzerland Swiss Cheese" },
                    { 4607052403818m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/palochki_mocarelli_umalat_bondzhorno/", "Палочки моцареллы Умалат \\\"Бонджорно\\\"" },
                    { 4680016940018m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_mocarella_egorlik_moloko_mini/", "Сыр Моцарелла Егорлык молоко Mini" },
                    { 2313059002900m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/adigeyskiy_sir_molkombinat_adigeyskiy/", "Адыгейский сыр \\\"Молкомбинат Адыгейский\\\"" },
                    { 4770299390583m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_tverdiy_zhirniy_dziugas/", "Сыр твердый жирный Dziugas" },
                    { 4620770400723m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_krasnogvardeyskiy_molochniy_zavod_adigeyskiy/", "Сыр Красногвардейский молочный завод \\\"Адыгейский\\\"" },
                    { 4607052403702m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_mocarella_bez_laktozi_dlya_sendvichey_umalat_mozzarella_unagrande/", "Сыр моцарелла без лактозы для сэндвичей Umalat Mozzarella Unagrande" },
                    { 4607048553763m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_myagkiy_sir_selo_zelenoe_fermerskiy_zavtrak/", "Сыр мягкий Сыр Село Зеленое \\\"Фермерский завтрак\\\"" },
                    { 5900512220000m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_kislomolochniy_mlekovita_ganusi/", "Творог Mlekovita \\\"Гануси\\\" 6,5%" },
                    { 4690363076765m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_ashan_rikotta/", "Сыр Ашан \\\"Рикотта\\\"" },
                    { 4900512190408m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_swiatowid_gauda/", "Сыр Swiatowid \\\"Гауда\\\"" },
                    { 4607127280221m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_ip_agamiryan_v_s_suluguni/", "Сыр ИП Агамирян В.С. \\\"Сулугуни\\\"" },
                    { 4823061315588m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_kislomolochniy_romol_9_0/", "Сыр кисломолочный Ромол 9, 0%" },
                    { 3073780979528m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_leerdammer_original/", "Сыр Leerdammer \\\"Original\\\"" },
                    { 8011661001345m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_trentin_grana_padano/", "Сыр Trentin Grana Padano" },
                    { 4607048552339m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_suluguni_kaloriya_iz_staroy_derevni/", "Сыр Сулугуни Калория \\\"Из старой деревни\\\"" },
                    { 4607052403436m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/palochki_umalat_suluguni/", "Палочки Умалат \\\"Сулугуни\\\"" },
                    { 4011410690107m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_bellezza_mocarella/", "Сыр Bellezza \\\"Моцарелла\\\"" },
                    { 4630055991136m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_polutverdiy_ferma_dolyubovo_rossiyskiy/", "Сыр полутвердый Ферма Долюбово \\\"Российский\\\"" },
                    { 4607052402217m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_vash_vibor_mocarella_mini/", "Сыр Ваш выбор \\\"Моцарелла мини\\\"" },
                    { 5901390002672m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_delikate_blue_niebieski/", "Сыр Delikate Blue niebieski" },
                    { 20982218m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_bluedino_gauda/", "Сыр Bluedino Gauda" },
                    { 9263575612622m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_dobryana_kachiotto/", "Сыр Добряна \\\"Качиотто\\\"" },
                    { 7038010028885m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_tine_norway_gudbrandsdalen/", "Сыр TINE Norway Gudbrandsdalen" },
                    { 4606068277529m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_lenta_suluguni/", "Сыр Лента \\\"Сулугуни\\\"" },
                    { 2773473002083m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_tverdiy_piryatin_orehoviy_50/", "Сыр твердый Пирятин \\\"Ореховый\\\" 50%" },
                    { 2701786002667m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_novgorod-severskiy_sirzavod_rafael/", "Сыр Новгород-Северский сырзавод \\\"Рафаэль\\\"" },
                    { 4607024209899m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_myagkiy_starodub_kavkazskiy/?&capt4a=2", "Сыр мягкий Стародуб \\\"Кавказский\\\"" },
                    { 4607048552957m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_kezskiy_sirzavod_slivochniy/", "Сыр Кезский сырзавод \\\"Сливочный\\\"" },
                    { 4740572005053m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_estover_piimatoostus_hiirte_juust/", "Сыр Estover piimatoostus \\\"Hiirte Juust" },
                    { 4680034320280m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_vasha_ferma_chechil_spagetti/", "Сыр Ваша ферма \\\"Чечил спагетти\\\"" },
                    { 4650068534243m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_slivochniy_lukomore_shokoladniy/", "Сыр сливочный Лукоморье \\\"Шоколадный\\\"" },
                    { 2907450010352m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_le_superbe_switzerland_swiss/", "Сыр Le Superbe Switzerland Swiss" },
                    { 5902208000804m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_ryki_cezar/", "Сыр Ryki Цезарь" },
                    { 2100100072599m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_vkusvill_kachokavallo/", "Сыр ВкусВилл \\\"Качокавалло\\\"" },
                    { 4810557000783m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_berezovskiy_sirodelniy_kombinat_belovezhskiy_kopcheniy_s_percem_i_chesnokom/", "Сыр Березовский сыродельный комбинат \\\"Беловежский\\\" копченый с перцем и чесноком" },
                    { 4630032360429m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_myagkiy_sirnaya_gildiya_kamamber/", "Сыр мягкий Сырная Гильдия \\\"Камамбер\\\"" },
                    { 2100100082925m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_myagkiy_izbenka_byush_de_famil_s_beloy_plesenyu/", "Сыр мягкий \\\"Избенка\\\" Бюш де фамиль с белой плесенью" },
                    { 4607007644457m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_velikolukskiy_molochniy_kombinat_chedder_krasniy/", "Сыр Великолукский молочный комбинат Чеддер красный" },
                    { 2737695004904m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_slaviya_suluguni/", "Сыр Славия \\\"Сулугуни\\\"" },
                    { 2217440002480m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_o_green_adigeyskiy/", "Сыр OGreen \\\"Адыгейский\\\"" },
                    { 4607052401357m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_ungrande_maskarpone_gastronomicheskiy/", "Сыр Ungrande Маскарпоне гастрономический" },
                    { 2507642005724m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_frico_maasdam/", "Сыр Frico \\\"Маасдам\\\"" },
                    { 4607966161170m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_krasnogvardeyskiy_molochniy_zavod_assorti/", "Сыр Красногвардейский Молочный завод \\\"Ассорти\\\"" },
                    { 4640001731143m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_viola_plavleniy_vetchina_i_parmezan/", "Сыр Viola плавленый \\\"Ветчина и пармезан\\\"" },
                    { 2370645003109m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_pochinki_gauda_pochinki/", "Сыр Починки \\\"Гауда Починки\\\"" },
                    { 8594015246956m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/balkanskiy_sir_v_rassole_balsyr/", "Балканский сыр в рассоле Balsyr" },
                    { 4607003722715m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_domashniy_myagkiy_melike_s_tminom/", "Сыр домашний мягкий Melike с тмином" },
                    { 4607908056538m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_il_primo_gusto_mocarella/", "Сыр Il Primo Gusto \\\"Моцарелла\\\"" },
                    { 8600742011658m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/serbskiy_sir_mlekara_subotica_brinza/", "Сербский сыр Mlekara Subotica Брынза" },
                    { 4640001731761m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_polutverdiy_fasovanniy_valio_buterbrodniy/", "Сыр полутвердый фасованный Valio \\\"Бутербродный\\\"" },
                    { 4680046940124m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_dlya_zharki_egorlik_moloko_hallume_klassicheskiy/", "Сыр для жарки Егорлык Молоко \\\"Халлуме классический\\\"" },
                    { 6414893381087m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_epiim_kermaguusto_estonskiy_slivochniy/", "Сыр Epiim \\\"Kermaguusto\\\" эстонский сливочный" },
                    { 2877089003585m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/myagkiy_sir_ermitage_bri/", "Мягкий сыр Ermitage \\\"Бри\\\"" },
                    { 4607052401401m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_mozzarella_dlya_pizza_pretto/", "Сыр Mozzarella для пиццы \\\"Pretto\\\"" },
                    { 4607070735809m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_belebeevskiy_belebeevskiy/", "Сыр Белебеевский \\\"Белебеевский\\\"" },
                    { 4607052403689m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_mozzarella_unagrande_ciliegine_senza_lattosio_malenkie_shariki_bez_laktozi/", "Сыр Mozzarella Unagrande Ciliegine Senza Lattosio маленькие шарики без лактозы" },
                    { 8606003752728m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_myagkiy_kuc-company_serbskiy_kaymak/", "Сыр мягкий Kuc-Company Сербский каймак" },
                    { 230043002240m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_tommoloko_legenda_altaya/", "Сыр Томмолоко \\\"Легенда Алтая\\\"" },
                    { 4607108092751m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_cheezzi_chizano_s_pazhitnikom/", "Сыр Cheezzi Чизано с пажитником" },
                    { 607059883002m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_ichalki_mramorniy/", "Сыр Ичалки \\\"Мраморный\\\"" },
                    { 56058663m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_swiatowid_liliput/", "Сыр Swiatowid \\\"Liliput\\\"" },
                    { 4811485017546m, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "https://otzovik.com/reviews/sir_danke_slivochniy/", "Сыр Danke сливочный" }
                });
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "EntriesList");
        }
    }
}
