// <auto-generated />
using System;
using GoodBuyAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GoodBuyAPI.Migrations
{
    [DbContext(typeof(MyDatabaseContext))]
    partial class MyDatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GoodBuyAPI.Models.Entry", b =>
                {
                    b.Property<decimal>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(20,0)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Link")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("EntriesList");

                    b.HasData(
                        new
                        {
                            ID = 8600742014093m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/brinza_serbskaya_serbskiy_dom/",
                            Name = "Брынза сербская \\\"Сербский дом\\\""
                        },
                        new
                        {
                            ID = 4607052403818m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/palochki_mocarelli_umalat_bondzhorno/",
                            Name = "Палочки моцареллы Умалат \\\"Бонджорно\\\""
                        },
                        new
                        {
                            ID = 4680016940018m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_mocarella_egorlik_moloko_mini/",
                            Name = "Сыр Моцарелла Егорлык молоко Mini"
                        },
                        new
                        {
                            ID = 2313059002900m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/adigeyskiy_sir_molkombinat_adigeyskiy/",
                            Name = "Адыгейский сыр \\\"Молкомбинат Адыгейский\\\""
                        },
                        new
                        {
                            ID = 4770299390583m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_tverdiy_zhirniy_dziugas/",
                            Name = "Сыр твердый жирный Dziugas"
                        },
                        new
                        {
                            ID = 4620770400723m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_krasnogvardeyskiy_molochniy_zavod_adigeyskiy/",
                            Name = "Сыр Красногвардейский молочный завод \\\"Адыгейский\\\""
                        },
                        new
                        {
                            ID = 4607052403702m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_mocarella_bez_laktozi_dlya_sendvichey_umalat_mozzarella_unagrande/",
                            Name = "Сыр моцарелла без лактозы для сэндвичей Umalat Mozzarella Unagrande"
                        },
                        new
                        {
                            ID = 4607048553763m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_myagkiy_sir_selo_zelenoe_fermerskiy_zavtrak/",
                            Name = "Сыр мягкий Сыр Село Зеленое \\\"Фермерский завтрак\\\""
                        },
                        new
                        {
                            ID = 5900512220000m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_kislomolochniy_mlekovita_ganusi/",
                            Name = "Творог Mlekovita \\\"Гануси\\\" 6,5%"
                        },
                        new
                        {
                            ID = 4690363076765m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_ashan_rikotta/",
                            Name = "Сыр Ашан \\\"Рикотта\\\""
                        },
                        new
                        {
                            ID = 4900512190408m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_swiatowid_gauda/",
                            Name = "Сыр Swiatowid \\\"Гауда\\\""
                        },
                        new
                        {
                            ID = 4607127280221m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_ip_agamiryan_v_s_suluguni/",
                            Name = "Сыр ИП Агамирян В.С. \\\"Сулугуни\\\""
                        },
                        new
                        {
                            ID = 4823061315588m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_kislomolochniy_romol_9_0/",
                            Name = "Сыр кисломолочный Ромол 9, 0%"
                        },
                        new
                        {
                            ID = 3073780979528m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_leerdammer_original/",
                            Name = "Сыр Leerdammer \\\"Original\\\""
                        },
                        new
                        {
                            ID = 8011661001345m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_trentin_grana_padano/",
                            Name = "Сыр Trentin Grana Padano"
                        },
                        new
                        {
                            ID = 4607048552339m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_suluguni_kaloriya_iz_staroy_derevni/",
                            Name = "Сыр Сулугуни Калория \\\"Из старой деревни\\\""
                        },
                        new
                        {
                            ID = 4607052403436m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/palochki_umalat_suluguni/",
                            Name = "Палочки Умалат \\\"Сулугуни\\\""
                        },
                        new
                        {
                            ID = 4011410690107m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_bellezza_mocarella/",
                            Name = "Сыр Bellezza \\\"Моцарелла\\\""
                        },
                        new
                        {
                            ID = 4630073930025m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_laime_switzerland_swiss_cheese/",
                            Name = "Сыр Laime Switzerland Swiss Cheese"
                        },
                        new
                        {
                            ID = 4630055991136m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_polutverdiy_ferma_dolyubovo_rossiyskiy/",
                            Name = "Сыр полутвердый Ферма Долюбово \\\"Российский\\\""
                        },
                        new
                        {
                            ID = 8002004437259m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_biraghi_parmezan_biraghini_snack/",
                            Name = "Сыр Biraghi Пармезан Biraghini Snack"
                        },
                        new
                        {
                            ID = 2100100162924m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_vkusvill_mocarella_perlini/",
                            Name = "Сыр ВкусВилл \\\"Моцарелла перлини\\\""
                        },
                        new
                        {
                            ID = 4606068330194m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_lenta_adigeyskiy_kopcheniy/",
                            Name = "Сыр Лента Адыгейский копченый"
                        },
                        new
                        {
                            ID = 2341573002267m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_archa_gauda/",
                            Name = "Сыр Арча \\\"Гауда\\\""
                        },
                        new
                        {
                            ID = 4607028304712m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_rovenki-maslosirzavod_fresh/",
                            Name = "Сыр Ровеньки-маслосырзавод Fresh"
                        },
                        new
                        {
                            ID = 2100100159139m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_myagkiy_vkusvill_rikotta_s_shokoladom/",
                            Name = "Сыр мягкий ВкусВилл \\\"Рикотта с шоколадом\\\""
                        },
                        new
                        {
                            ID = 4680320008205m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_fasovanniy_tertiy_milken_mite_dlya_picci/",
                            Name = "Сыр фасованный тертый Milken Mite для пиццы"
                        },
                        new
                        {
                            ID = 5703985070383m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_s_goluboy_plesenyu_danablu_mammen_ost/",
                            Name = "Сыр с голубой плесенью Danablu Mammen OST"
                        },
                        new
                        {
                            ID = 465011743020m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_altayskie_sirovari_gollandskiy/",
                            Name = "Сыр Алтайские сыровары \\\"Голландский\\\""
                        },
                        new
                        {
                            ID = 4610032580072m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_nikolaevskie_sirovarni_kostromskoy/",
                            Name = "Сыр Николаевские сыроварни \\\"Костромской\\\""
                        },
                        new
                        {
                            ID = 4607052402880m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_market_perekrestok_suluguni/",
                            Name = "Сыр Маркет Перекресток \\\"Сулугуни\\\""
                        },
                        new
                        {
                            ID = 4601363002241m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_skit_skarmoca_cheldzhine_kopcheniy/",
                            Name = "Сыр Скит \\\"Скармоца Чьельджине\\\" копченый"
                        },
                        new
                        {
                            ID = 4779024794696m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/produkt_veganskiy_regalio_s_zelenyu/",
                            Name = "Продукт веганский Regalio с зеленью"
                        },
                        new
                        {
                            ID = 20532031m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_antichi_maestri_parmigiano_reggiano_dop/gallery/",
                            Name = "Сыр Antichi Maestri Parmigiano Reggiano DOP"
                        },
                        new
                        {
                            ID = 4610004671449m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_sarmich_chedder/",
                            Name = "Сыр Сармич \\\"Чеддер\\\""
                        },
                        new
                        {
                            ID = 20536718m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_pilos_camembert_naturalniy/",
                            Name = "Сыр Pilos Camembert натуральный"
                        },
                        new
                        {
                            ID = 2546953003487m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_beloslava_sirniy_aristokrat_50_vesovoy/gallery/",
                            Name = "Сыр Белослава \\\"Сырный аристократ\\\" 50%"
                        },
                        new
                        {
                            ID = 2100100004163m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_izbenka_gran-pri/",
                            Name = "Сыр Избенка \\\"Гран-При\\\""
                        },
                        new
                        {
                            ID = 4607195114022m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_chaban_suluguni/",
                            Name = "Сыр Чабан \\\"Сулугуни\\\""
                        },
                        new
                        {
                            ID = 2510348003581m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_myagkiy_slivochniy_holifud_chezariya/",
                            Name = "Сыр мягкий сливочный ХолиФуд \\\"Чезария\\\""
                        },
                        new
                        {
                            ID = 4607052402217m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_vash_vibor_mocarella_mini/",
                            Name = "Сыр Ваш выбор \\\"Моцарелла мини\\\""
                        },
                        new
                        {
                            ID = 5901390002672m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_delikate_blue_niebieski/",
                            Name = "Сыр Delikate Blue niebieski"
                        },
                        new
                        {
                            ID = 20982218m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_bluedino_gauda/",
                            Name = "Сыр Bluedino Gauda"
                        },
                        new
                        {
                            ID = 4607966161170m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_krasnogvardeyskiy_molochniy_zavod_assorti/",
                            Name = "Сыр Красногвардейский Молочный завод \\\"Ассорти\\\""
                        },
                        new
                        {
                            ID = 4640001731143m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_viola_plavleniy_vetchina_i_parmezan/",
                            Name = "Сыр Viola плавленый \\\"Ветчина и пармезан\\\""
                        },
                        new
                        {
                            ID = 2370645003109m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_pochinki_gauda_pochinki/",
                            Name = "Сыр Починки \\\"Гауда Починки\\\""
                        },
                        new
                        {
                            ID = 8594015246956m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/balkanskiy_sir_v_rassole_balsyr/",
                            Name = "Балканский сыр в рассоле Balsyr"
                        },
                        new
                        {
                            ID = 4607003722715m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_domashniy_myagkiy_melike_s_tminom/",
                            Name = "Сыр домашний мягкий Melike с тмином"
                        },
                        new
                        {
                            ID = 4607908056538m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_il_primo_gusto_mocarella/",
                            Name = "Сыр Il Primo Gusto \\\"Моцарелла\\\""
                        },
                        new
                        {
                            ID = 8600742011658m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/serbskiy_sir_mlekara_subotica_brinza/",
                            Name = "Сербский сыр Mlekara Subotica Брынза"
                        },
                        new
                        {
                            ID = 4640001731761m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_polutverdiy_fasovanniy_valio_buterbrodniy/",
                            Name = "Сыр полутвердый фасованный Valio \\\"Бутербродный\\\""
                        },
                        new
                        {
                            ID = 6414893381087m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_epiim_kermaguusto_estonskiy_slivochniy/",
                            Name = "Сыр Epiim \\\"Kermaguusto\\\" эстонский сливочный"
                        },
                        new
                        {
                            ID = 56058663m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_swiatowid_liliput/",
                            Name = "Сыр Swiatowid \\\"Liliput\\\""
                        },
                        new
                        {
                            ID = 2877089003585m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/myagkiy_sir_ermitage_bri/",
                            Name = "Мягкий сыр Ermitage \\\"Бри\\\""
                        },
                        new
                        {
                            ID = 4607052401401m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_mozzarella_dlya_pizza_pretto/",
                            Name = "Сыр Mozzarella для пиццы \\\"Pretto\\\""
                        },
                        new
                        {
                            ID = 4607070735809m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_belebeevskiy_belebeevskiy/",
                            Name = "Сыр Белебеевский \\\"Белебеевский\\\""
                        },
                        new
                        {
                            ID = 4607052403689m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_mozzarella_unagrande_ciliegine_senza_lattosio_malenkie_shariki_bez_laktozi/",
                            Name = "Сыр Mozzarella Unagrande Ciliegine Senza Lattosio маленькие шарики без лактозы"
                        },
                        new
                        {
                            ID = 8606003752728m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_myagkiy_kuc-company_serbskiy_kaymak/",
                            Name = "Сыр мягкий Kuc-Company Сербский каймак"
                        },
                        new
                        {
                            ID = 230043002240m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_tommoloko_legenda_altaya/",
                            Name = "Сыр Томмолоко \\\"Легенда Алтая\\\""
                        },
                        new
                        {
                            ID = 4607108092751m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_cheezzi_chizano_s_pazhitnikom/",
                            Name = "Сыр Cheezzi Чизано с пажитником"
                        },
                        new
                        {
                            ID = 607059883002m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_ichalki_mramorniy/",
                            Name = "Сыр Ичалки \\\"Мраморный\\\""
                        },
                        new
                        {
                            ID = 2507642005724m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_frico_maasdam/",
                            Name = "Сыр Frico \\\"Маасдам\\\""
                        },
                        new
                        {
                            ID = 4607052401357m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_ungrande_maskarpone_gastronomicheskiy/",
                            Name = "Сыр Ungrande Маскарпоне гастрономический"
                        },
                        new
                        {
                            ID = 2217440002480m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_o_green_adigeyskiy/",
                            Name = "Сыр OGreen \\\"Адыгейский\\\""
                        },
                        new
                        {
                            ID = 2737695004904m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_slaviya_suluguni/",
                            Name = "Сыр Славия \\\"Сулугуни\\\""
                        },
                        new
                        {
                            ID = 9263575612622m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_dobryana_kachiotto/",
                            Name = "Сыр Добряна \\\"Качиотто\\\""
                        },
                        new
                        {
                            ID = 7038010028885m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_tine_norway_gudbrandsdalen/",
                            Name = "Сыр TINE Norway Gudbrandsdalen"
                        },
                        new
                        {
                            ID = 4606068277529m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_lenta_suluguni/",
                            Name = "Сыр Лента \\\"Сулугуни\\\""
                        },
                        new
                        {
                            ID = 2773473002083m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_tverdiy_piryatin_orehoviy_50/",
                            Name = "Сыр твердый Пирятин \\\"Ореховый\\\" 50%"
                        },
                        new
                        {
                            ID = 2701786002667m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_novgorod-severskiy_sirzavod_rafael/",
                            Name = "Сыр Новгород-Северский сырзавод \\\"Рафаэль\\\""
                        },
                        new
                        {
                            ID = 4607024209899m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_myagkiy_starodub_kavkazskiy/?&capt4a=2",
                            Name = "Сыр мягкий Стародуб \\\"Кавказский\\\""
                        },
                        new
                        {
                            ID = 4607048552957m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_kezskiy_sirzavod_slivochniy/",
                            Name = "Сыр Кезский сырзавод \\\"Сливочный\\\""
                        },
                        new
                        {
                            ID = 4740572005053m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_estover_piimatoostus_hiirte_juust/",
                            Name = "Сыр Estover piimatoostus \\\"Hiirte Juust"
                        },
                        new
                        {
                            ID = 4680034320280m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_vasha_ferma_chechil_spagetti/",
                            Name = "Сыр Ваша ферма \\\"Чечил спагетти\\\""
                        },
                        new
                        {
                            ID = 4650068534243m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_slivochniy_lukomore_shokoladniy/",
                            Name = "Сыр сливочный Лукоморье \\\"Шоколадный\\\""
                        },
                        new
                        {
                            ID = 2907450010352m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_le_superbe_switzerland_swiss/",
                            Name = "Сыр Le Superbe Switzerland Swiss"
                        },
                        new
                        {
                            ID = 5902208000804m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_ryki_cezar/",
                            Name = "Сыр Ryki Цезарь"
                        },
                        new
                        {
                            ID = 2100100072599m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_vkusvill_kachokavallo/",
                            Name = "Сыр ВкусВилл \\\"Качокавалло\\\""
                        },
                        new
                        {
                            ID = 4810557000783m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_berezovskiy_sirodelniy_kombinat_belovezhskiy_kopcheniy_s_percem_i_chesnokom/",
                            Name = "Сыр Березовский сыродельный комбинат \\\"Беловежский\\\" копченый с перцем и чесноком"
                        },
                        new
                        {
                            ID = 4630032360429m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_myagkiy_sirnaya_gildiya_kamamber/",
                            Name = "Сыр мягкий Сырная Гильдия \\\"Камамбер\\\""
                        },
                        new
                        {
                            ID = 2100100082925m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_myagkiy_izbenka_byush_de_famil_s_beloy_plesenyu/",
                            Name = "Сыр мягкий \\\"Избенка\\\" Бюш де фамиль с белой плесенью"
                        },
                        new
                        {
                            ID = 4607007644457m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_velikolukskiy_molochniy_kombinat_chedder_krasniy/",
                            Name = "Сыр Великолукский молочный комбинат Чеддер красный"
                        },
                        new
                        {
                            ID = 4002174205379m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/shveycarskiy_sir_margot_fromages_sa_tete_de_moine/",
                            Name = "Швейцарский сыр Margot Fromages Sa Tete de Moine"
                        },
                        new
                        {
                            ID = 3161712996146m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_ile_de_franse_petit_brie/",
                            Name = "Сыр ILE de Franse Petit Brie"
                        },
                        new
                        {
                            ID = 4811832000795m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_kopcheniy_glubokskaya_pticefabrika_dzhil/",
                            Name = "Сыр копченый Глубокская птицефабрика \\\"Джил\\\""
                        },
                        new
                        {
                            ID = 7610563606392m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_le_superbe_services_ag_lustenberger_1862_fruity_tangy/",
                            Name = "Сыр Le Superbe Services AG \\\"Lustenberger 1862 fruity tangy\\\""
                        },
                        new
                        {
                            ID = 2104779003403m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_holod_adigeyskiy/",
                            Name = "Сыр Холод \\\"Адыгейский\\\""
                        },
                        new
                        {
                            ID = 4607044667426m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_suhoy_kopcheniy_foma_lukich_bochonok/",
                            Name = "Сыр сухой копченый Фома Лукич \\\"Бочонок\\\""
                        },
                        new
                        {
                            ID = 5900120061729m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_swiatowid_salami/",
                            Name = "Сыр Swiatowid Salami"
                        },
                        new
                        {
                            ID = 4700000140053m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/kolbasniy_sir_belovodskiy_maslosirzavod/",
                            Name = "Колбасный сыр \\\"Беловодский маслосырзавод\\\""
                        },
                        new
                        {
                            ID = 2000063640012m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_dlya_zharki_myasnov_sernurskiy_halumis/",
                            Name = "Сыр для жарки МясновЪ \\\"Сернурский Халумис\\\""
                        },
                        new
                        {
                            ID = 4810904000480m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_kuvshinka_suluguni/",
                            Name = "Сыр Кувшинка \\\"Сулугуни\\\""
                        },
                        new
                        {
                            ID = 4810012003106m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_novogrudskie_dari_adigeyskiy_klassicheskiy/",
                            Name = "Сыр Новогрудские дары \\\"Адыгейский классический\\\""
                        },
                        new
                        {
                            ID = 4627128150040m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/soeviy_sir_edemskiy_sad_tofu/",
                            Name = "Соевый сыр Едемский сад \\\"Тофу\\\""
                        },
                        new
                        {
                            ID = 4740553698113m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_parmezan_valio_forte/",
                            Name = "Сыр пармезан Valio Forte"
                        },
                        new
                        {
                            ID = 7640106051211m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_myagkiy_moser_schweizer_huus_chasli_huus_chasli_s_beloy_plesenyu/",
                            Name = "Сыр мягкий Moser Schweizer Huus Chasli Хуус Часли с белой плесенью"
                        },
                        new
                        {
                            ID = 8021398443905m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_igor_gorgonzola_piccante/",
                            Name = "Сыр Igor Gorgonzola Piccante"
                        },
                        new
                        {
                            ID = 4607141170720m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_s_pazhitnikom_produkti_iz_yaroslavki_mologa/",
                            Name = "Сыр с пажитником Продукты из Ярославки \\\"Молога\\\""
                        },
                        new
                        {
                            ID = 4607022663242m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_president_la_brique/",
                            Name = "Сыр President La Brique"
                        },
                        new
                        {
                            ID = 7617067036328m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_haidi_swiss_ceddar/",
                            Name = "Сыр Haidi Swiss Ceddar"
                        },
                        new
                        {
                            ID = 4607025501992m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_myagkiy_sheksninskiy_maslozavod_adigeyskiy/",
                            Name = "Сыр мягкий Шекснинский маслозавод \\\"Адыгейский\\\""
                        },
                        new
                        {
                            ID = 4820009352636m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_tverdiy_zveni_gora_figura/",
                            Name = "Сыр твердый Звени Гора Фигура"
                        },
                        new
                        {
                            ID = 40409801m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_s_goluboy_plesenyu_paladin_fromage_bleu/",
                            Name = "Сыр с голубой плесенью Paladin \\\"Fromage bleu\\\""
                        },
                        new
                        {
                            ID = 4740142003786m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_epiim_edamjuusto/",
                            Name = "Сыр Epiim Edamjuusto"
                        },
                        new
                        {
                            ID = 5900512130408m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/tverdiy_sir_biedronka_serovit_gouda/",
                            Name = "Твердый сыр Biedronka Serovit Gouda"
                        },
                        new
                        {
                            ID = 2000000000626m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_podvore_mocarella/",
                            Name = "Сыр Подворье \\\"Моцарелла\\\""
                        },
                        new
                        {
                            ID = 2201956900545m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_cheese_life_mozzarella_pizza/",
                            Name = "Сыр Cheese Life \\\"Mozzarella Pizza\\\""
                        },
                        new
                        {
                            ID = 8004603100381m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_antichi_maestri_grana_padano/",
                            Name = "Сыр Antichi Maestri \\\"Grana Padano\\\""
                        },
                        new
                        {
                            ID = 4607074392442m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_zorka_adigeyskiy_delikatesniy/",
                            Name = "Сыр Zorka \\\"Адыгейский деликатесный\\\""
                        },
                        new
                        {
                            ID = 4607946840439m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_zdorove_iz_predgorya_fermerskiy/",
                            Name = "Сыр Здоровье из Предгорья \\\"Фермерский\\\""
                        },
                        new
                        {
                            ID = 3523230028431m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_koziy_soignon/",
                            Name = "Сыр козий Soignon"
                        },
                        new
                        {
                            ID = 4820111642359m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_dobryana_zolotistiy/",
                            Name = "Сыр Добряна \\\"Золотистый\\\""
                        },
                        new
                        {
                            ID = 20933883m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_milbona_maasdam_finskiy/",
                            Name = "Сыр Milbona Маасдам финский"
                        },
                        new
                        {
                            ID = 20014254m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_milbona/",
                            Name = "Сыр Milbona"
                        },
                        new
                        {
                            ID = 2310369000930m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_novogrudskie_dari_pesto/",
                            Name = "Сыр Новогрудские Дары \\\"Песто\\\""
                        },
                        new
                        {
                            ID = 8692971434919m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_tureckiy_halk_taze_kasar_peyniri/",
                            Name = "Сыр турецкий Halk Taze Kasar Peyniri"
                        },
                        new
                        {
                            ID = 4607127280054m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_myagkiy_rovenki_adigeyskiy_45/",
                            Name = "Сыр мягкий Ровеньки \\\"Адыгейский\\\" 45%"
                        },
                        new
                        {
                            ID = 5760466827225m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_s_goluboy_plesenyu_castello_danish_blue_slivochniy/",
                            Name = "Сыр с голубой плесенью Castello Danish Blue \\\"Сливочный\\\""
                        },
                        new
                        {
                            ID = 3073781053821m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_leerdammer_llightlife_17/",
                            Name = "Сыр Leerdammer Llightlife 17%"
                        },
                        new
                        {
                            ID = 6408432052705m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/kopcheniy_sir_viola_s_salyami/",
                            Name = "Копченый сыр Viola с салями"
                        },
                        new
                        {
                            ID = 3272770003148m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/svezhiy_sir_iz_kozego_moloka_bongrain_chavroux/",
                            Name = "Свежий сыр из козьего молока Bongrain \\\"Chavroux\\\""
                        },
                        new
                        {
                            ID = 4606068378707m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_lenta_fermerskiy/",
                            Name = "Сыр Лента \\\"Фермерский\\\""
                        },
                        new
                        {
                            ID = 2393876003304m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_liebendorf_maasdam/?&capt4a=2",
                            Name = "Сыр LiebenDorf Маасдам"
                        },
                        new
                        {
                            ID = 4650100420497m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_s_beloy_plesenyu_zhukovskoe_moloko_camambert_from_zhukovka/",
                            Name = "Сыр с белой плесенью Жуковское молоко Camambert from Zhukovka"
                        },
                        new
                        {
                            ID = 4607052402378m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/myagkiy_sir_pretto_maskarpone/",
                            Name = "Мягкий сыр Pretto \\\"Маскарпоне\\\""
                        },
                        new
                        {
                            ID = 2844830000629m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_mifroma_sa_tet_de_muan/",
                            Name = "Сыр Mifroma Sa \\\"Тет де Муан\\\""
                        },
                        new
                        {
                            ID = 4607052401302m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_unagrande_mocarella_chiledzhina/gallery/",
                            Name = "Сыр Unagrande \\\"Моцарелла Чильеджина\\\""
                        },
                        new
                        {
                            ID = 4680038890376m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_myagkiy_slivkin_dom_rikotta/",
                            Name = "Сыр мягкий Сливкин дом \\\"Рикотта\\\""
                        },
                        new
                        {
                            ID = 4650167850336m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_beloe_zoloto_adigeyskiy_iz_kozego_moloka/",
                            Name = "Сыр Белое Золото Адыгейский из Козьего молока"
                        },
                        new
                        {
                            ID = 4607002022618m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_violife_legkiy/",
                            Name = "Сыр Violife \\\"Легкий\\\""
                        },
                        new
                        {
                            ID = 4660059528045m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_fermerskaya_kollekciya_rikotta_45/",
                            Name = "Сыр Фермерская коллекция \\\"Рикотта\\\" 45%"
                        },
                        new
                        {
                            ID = 2999200013669m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_de_luxe_maasdam/",
                            Name = "Сыр De Luxe Maasdam"
                        },
                        new
                        {
                            ID = 4607128362391m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_o_key_domashniy_po-kavkazski/",
                            Name = "Сыр ОКей Домашний по-кавказски"
                        },
                        new
                        {
                            ID = 4610032582106m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_nikolaevskie_sirovarni_myagkiy_fermerskiy/",
                            Name = "Сыр Николаевские сыроварни \\\"Мягкий\\\" фермерский"
                        },
                        new
                        {
                            ID = 2787241003424m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_piryatin_mramorniy/",
                            Name = "Сыр Пирятин \\\"Мраморный\\\""
                        },
                        new
                        {
                            ID = 5900512990224m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_mlekovita_salami/",
                            Name = "Сыр Mlekovita Salami"
                        },
                        new
                        {
                            ID = 2100100030582m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/tofu_vkusvill_s_ukropom_i_chesnokom/",
                            Name = "Тофу ВкусВилл \\\"С укропом и чесноком\\\""
                        },
                        new
                        {
                            ID = 4606038038891m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_myagkiy_zelenaya_liniya_s_tomatom_i_bazilikom/",
                            Name = "Сыр мягкий Зеленая Линия с томатом и базиликом"
                        },
                        new
                        {
                            ID = 4630061740896m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_dzhankoyskiy_sir_mocarella/",
                            Name = "Сыр Джанкойский сыр \\\"Моцарелла\\\""
                        },
                        new
                        {
                            ID = 4607052402392m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_myagkiy_unagrande_cacioricotta/",
                            Name = "Сыр мягкий Unagrande Cacioricotta"
                        },
                        new
                        {
                            ID = 2100100102951m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_vkusvill_sbrinc/",
                            Name = "Сыр ВкусВилл \\\"Сбринц\\\""
                        },
                        new
                        {
                            ID = 2000243003101m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_radost_vkusa_rizhiy_chedder/",
                            Name = "Сыр Радость вкуса \\\"Рыжий Чеддер\\\""
                        },
                        new
                        {
                            ID = 4810904001418m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_landers_suluguni/",
                            Name = "Сыр Landers \\\"Сулугуни\\\""
                        },
                        new
                        {
                            ID = 4665296191991m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_s_beloy_plesenyu_fratelli_spirini_monblan/",
                            Name = "Сыр с белой плесенью Fratelli Spirini Монблан"
                        },
                        new
                        {
                            ID = 4620016651018m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_perekrestok_mocarella_dlya_picci/",
                            Name = "Сыр Перекресток Моцарелла для пиццы"
                        },
                        new
                        {
                            ID = 4620016651032m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_market_perekrestok_kamamber/",
                            Name = "Сыр Маркет Перекресток \\\"Камамбер\\\""
                        },
                        new
                        {
                            ID = 2100100005481m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_izbenka_gollandskiy/",
                            Name = "Сыр Избенка \\\"Голландский\\\""
                        },
                        new
                        {
                            ID = 8023951002550m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_ghidetti_maskarpone/",
                            Name = "Сыр Ghidetti \\\"Маскарпоне\\\""
                        },
                        new
                        {
                            ID = 5902241216798m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_makro_chef_ser_camembert/",
                            Name = "Сыр Makro Chef Ser Camembert"
                        },
                        new
                        {
                            ID = 2100100147600m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_s_goluboy_plesenyu_izbenka_dzhersi_blyu/",
                            Name = "Сыр с голубой плесенью Избенка \\\"Джерси Блю\\\""
                        },
                        new
                        {
                            ID = 4603209002477m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_ruzskoe_moloko_ruzskiy_pryaniy/",
                            Name = "Сыр Рузское молоко \\\"Рузский\\\" Пряный"
                        },
                        new
                        {
                            ID = 6402410119556m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_valio_oltermanni_29/",
                            Name = "Сыр Valio Oltermanni"
                        },
                        new
                        {
                            ID = 2100100093068m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_myagkiy_rassolniy_izbenka_sirtos/",
                            Name = "Сыр мягкий рассольный Избенка Сиртос"
                        },
                        new
                        {
                            ID = 4620016650448m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_market_perekrestok_mocarella/",
                            Name = "Сыр Маркет Перекресток \\\"Моцарелла\\\""
                        },
                        new
                        {
                            ID = 6260161533630m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/slivochniy_sir_kalleh/",
                            Name = "Сливочный сыр Kalleh"
                        },
                        new
                        {
                            ID = 4000504149423m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_myagkiy_kaserei_champignon_cambozola_s_goluboy_plesenyu/",
                            Name = "Сыр мягкий Kaserei Champignon Cambozola с голубой плесенью"
                        },
                        new
                        {
                            ID = 2100100073022m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_myagkiy_vkusvill_bri/",
                            Name = "Сыр мягкий ВкусВилл \\\"Бри\\\""
                        },
                        new
                        {
                            ID = 4520019492598m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/kislomolochniy_sir_belocerkovskiy_molokozavod_domashniy_5/",
                            Name = "Кисломолочный сыр Белоцерковский молокозавод \\\"Домашний\\\""
                        },
                        new
                        {
                            ID = 4607048552919m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_milkom_tilziter/",
                            Name = "Сыр Милком \\\"Тильзитэр\\\""
                        },
                        new
                        {
                            ID = 4740553691152m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_bezlaktozniy_valio_atleet/",
                            Name = "Сыр безлактозный Valio \\\"Atleet\\\""
                        },
                        new
                        {
                            ID = 4627075491061m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/bobrovskiy_sir_polutverdiy_slivochniy/",
                            Name = "Сыр полутвердый Бобровский \\\"Сливочный\\\""
                        },
                        new
                        {
                            ID = 5711953033926m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_arla_loputon_kermajuusto_17/",
                            Name = "Сыр Arla Loputon Kermajuusto"
                        },
                        new
                        {
                            ID = 4811233001964m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_myagkiy_rassolniy_molodeya_mocarella/",
                            Name = "Сыр мягкий рассольный Молодея \\\"Моцарелла\\\""
                        },
                        new
                        {
                            ID = 4607050960818m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_kopcheniy_kosichka_ellazan/",
                            Name = "Сыр копченый косичка Эллазан"
                        },
                        new
                        {
                            ID = 2370150010241m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_osobiy_sarmich_russkiy_sir_fasovanniy/",
                            Name = "Сыр особый Сармич \\\"Гурман\\\" фасованный"
                        },
                        new
                        {
                            ID = 4820040746616m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_kislomolochniy_dobrinya_9/",
                            Name = "Сыр кисломолочный Добрыня"
                        },
                        new
                        {
                            ID = 4680046940124m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_dlya_zharki_egorlik_moloko_hallume_klassicheskiy/",
                            Name = "Сыр для жарки Егорлык Молоко \\\"Халлуме классический\\\""
                        },
                        new
                        {
                            ID = 4811485017546m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://otzovik.com/reviews/sir_danke_slivochniy/",
                            Name = "Сыр Danke сливочный"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
